POST http://localhost:3001/api/exercises/miercoles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmEzOGQ2ZGEzNzRiNzcxOWVmM2U2NiIsInVzZXJuYW1lIjoiYXNkIiwiaWF0IjoxNzgxMTUyOTY3fQ.sPgB5RAY_UMxoOmANKUhCHotaWLMwjisITZezWwGaOc

{
    "dia": "miercoles",

    "name": "press plano",

    "series": 3,

    "reps": 11,

    "peso": 45,

    "user": "6a2a38d6da374b7719ef3e66"
}